### ISSUE TITLE
Test failures on fresh install [BUG]

### ISSUE THREAD

**Issue by mcelaney** [fastruby/pecas#99]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

main

**Expected behavior:**

Test suite should pass

**Actual behavior:**

11 failures

```
rspec ./spec/models/project_leaderboard_spec.rb:11
rspec ./spec/models/project_leaderboard_spec.rb:21
rspec ./spec/models/project_leaderboard_spec.rb:35
rspec ./spec/models/project_leaderboard_spec.rb:45
rspec ./spec/models/user_leaderboard_spec.rb:12
rspec ./spec/models/user_leaderboard_spec.rb:22
rspec ./spec/models/user_leaderboard_spec.rb:38
rspec ./spec/models/user_leaderboard_spec.rb:48
rspec ./spec/models/user_spec.rb:11
rspec ./spec/models/user_spec.rb:44
rspec ./spec/services/noko_service_spec.rb:29
```

**Steps to reproduce:**

1. Perform a fresh install of Pecas from Main
2. `docker-compose run web /bin/bash`
3. `bundle exec rspec`

It would appear the tests are written expecting a specific state for Noko - so my last time entry appears to cause an error:

```
  11) NokoService#import_entries with new entries creates the new entries in the database
      Failure/Error: expect(entry.description).to eql("Hello!")
      
        expected: "Hello!"
             got: "Develop Time Entry validation service for Pecas"
      
        (compared using eql?)
      # ./spec/services/noko_service_spec.rb:35:in `block (4 levels) in <top (required)>'
      # ./spec/rails_helper.rb:78:in `block (3 levels) in <top (required)>'
      # /usr/local/bundle/gems/vcr-6.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
      # /usr/local/bundle/gems/vcr-6.0.0/lib/vcr.rb:194:in `use_cassette'
      # ./spec/rails_helper.rb:78:in `block (2 levels) in <top (required)>'
      # /usr/local/bundle/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

`"Develop Time Entry validation service for Pecas"` is the description from my most recent time entry

**Context and environment:**

Provide any relevant information about your setup (Customize the list accordingly based on what info is relevant to this project)

1. Version of the software the issue is being opened for.

dcf99ca

**I will abide by the [code of conduct](https://github.com/fastruby/pecas/blob/main/code-of-conduct.md)**

**Comment by mcelaney** [comment]
Seems to be a local issue for me - I've got it fixed and can't seem to force the issue to happen again so I'm gonna close this.
